name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@just
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,bioconda
          activate-environment: camlhmp
          environment-file: environment.yml
          auto-update-conda: true
      - name: Install project
        run: |
          python -m pip install -U pip
          pip install poetry
          just install
      - name: Build a binary wheel and a source tarball
        run: just build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
